#!/usr/bin/env bash

# check that number of arguments is 1
if [[ "$#" -ne 1 ]]; then
    echo "ERROR: expected 1 argument" >&2
    exit 1
fi

err=0

# TODO: autodetect in & out files: ls *.in | wc -w == 1

# check if in/out files exist
if [[ ! -f "$1.in" ]]; then
    err=1
    echo "ERROR: $1.in not found" >&2
fi

if [[ ! -f "$1.out" ]]; then
    err=1
    echo "ERROR: $1.out not found" >&2
fi

if [[ "$err" -eq 1 ]]; then
    exit 1
fi

base=$(basename "$PWD")

if ! g++ -std=c++11 -Wall -o "$base" "$base.cpp"; then
    echo "ERROR: compilation error" >&2
    exit 1
fi

if ! "./$base" < "$1.in" > "$base.out"; then
    echo "ERROR: runtime error" >&2
    err=1
else
    if diff "$1.out" "$base.out"; then
        echo "Output matches :)"
    else
        echo "Output does NOT match :("
    fi
fi

rm "$base" "$base.out"

if [[ "$err" -eq 1 ]]; then
    exit 1
fi
